# base image
FROM node:11.6.0-alpine

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
# COPY yarn.lock /usr/src/app/yarn.lock
RUN npm install
RUN npm install react-scripts@2.1.3 -g

# copy webpackDevServer config with modified watchOptions 
# where poll: 3000  is added to check for changes every 3 seconds
# this gives a 'warm' reload ability when working with webpack in 
# docker container on Microsoft Windows
COPY WindowsDockerReact/webpackDevServer.config.js /usr/src/app/node_modules/react-scripts/config/webpackDevServer.config.js

# start app
CMD ["npm", "start"]